testname: Voice Conversion Hörversuch
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
language: de
remoteService: service/write.php


pages:
    - type: consent
      id: consent_page
      name: Einverständniserklärung
      mustConsent: true
      content: <p>Sie sind im Begriff, an einem wissenschaftlichen Hörversuch teilzunehmen.<br>Ihre Antworten werden für die statistische Auswertung anonymisiert gespeichert.</p><p>Sind Sie damit einverstanden?</p>
    - type: volume
      id: volume_page
      name: Einleitung
      content: <p>Willkommen zu unserem Online-Hörversuch!</p><p>Auf den folgenden Seiten werden Ihnen einige Sprachaufnahmen präsentiert. Ihre Aufgabe ist es, die Sprachaufnahmen anhand der jeweils angegebenen Qualitätskriterien zu bewerten.</p><hr><p>Nutzen Sie diese Beispielaufnahme, um die Lautstärke auf ein angenehmes Niveau anzupassen.<br>Bitte ändern Sie die Lautstärke Ihres Endgerätes für den weiteren Verlauf des Hörversuchs nicht mehr.</p>
      stimulus: configs/resources/audio/kennedy_moon.wav
      defaultVolume: 0.5
    - type: likert_multi_stimulus
      id: lms2
      name: Likert
      content: <p>Spielen Sie die Aufnahme ab und bewerten Sie die Qualität von 1-4.<br><small>(1 = am schlechtesten, 4 = am besten)</small></p>
      mustRate: true
      stimuli:
          C1: configs/resources/audio/trump_lowest.wav
      response:
        - value: not at all
          label: 1
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: not a lot
          label: 2
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: a bit
          label: 3
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: much
          label: 4
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
    - type: paired_comparison
      id: AB_noloop
      name: AB-Test
      unforced: 
      content: Wählen Sie
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/kennedy_moon.wav
      stimuli:
        C1: configs/resources/audio/biden_moon.wav
    - type: bs1116
      id: bs1116_nowav
      name: BS 11.16 test
      content: This is a BS1116 page.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/biden_lowest.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
        C1: configs/resources/audio/female_lowest.wav
    - type: mushra
      id: mushra
      name: MUSHRA 
      content: This is a MUSHRA page with enabled looping and waveform but without anchors.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/trump_lowest.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
        C1: configs/resources/audio/biden_lowest.wav
        C2: configs/resources/audio/female_lowest.wav
    - type: finish
      name: Fast fertig!
      content: Bitte füllen Sie das folgende Formular aus, um das Experiment abzuschließen.
      showResults: false
      writeResults: true
      questionnaire:
          - type: number
            label: Alter
            name: age
            min: 0
            max: 100
            default: 20
          - type: likert
            name: gender
            label: Geschlecht
            response:
             - value: female
               label: Frau
             - value: male
               label: Mann
